Repository HLCA-CNRI/cnri_homepage, pull requests merged in 2022-11, with the labels that each got.

#86 [FeatDone] LCA project guide page created
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_plan.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE/documentation.md
  .github/PULL_REQUEST_TEMPLATE/feature_done.md
  .github/issue_template.md
  .github/pull_request_template.md
  components/LCAComponents/SectionDetail.tsx
  components/Layout.tsx
  components/PopUp.tsx
  package-lock.json
  package.json
  pages/lca/index.tsx
  public/images/lca/icon_arrow.svg
  public/images/lca/icon_check.svg
  public/images/lca/section1.png
  public/images/lca/section2.png
  public/images/lca/section3.png
  yarn.lock
Labels: 분류: 기능 구현

#87 HOMEPAGE-23 [FeatDone] LCA project guide page re-design
  components/LCAComponents/SectionDetail.tsx
  pages/lca/index.tsx
Labels: 분류: 기능 구현

#88 HOMEPAGE-23 [FeatDone] LCA project guide page created (applied in main)
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_plan.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE/documentation.md
  .github/PULL_REQUEST_TEMPLATE/feature_done.md
  .github/issue_template.md
  .github/pull_request_template.md
  components/LCAComponents/SectionDetail.tsx
  components/Layout.tsx
  components/PopUp.tsx
  package-lock.json
  package.json
  pages/lca/index.tsx
  public/images/lca/icon_arrow.svg
  public/images/lca/icon_check.svg
  public/images/lca/section1.png
  public/images/lca/section2.png
  public/images/lca/section3.png
  yarn.lock
Labels: 분류: 기능 구현

#89 [BugFix] LCA Project page UI fixed
  components/LCAComponents/SectionDetail.tsx
  pages/lca/index.tsx
  public/images/lca/section1.png
  public/images/lca/section3.png
Labels: 분류: 버그

#90 [BugFix] safari details triangle disabled
  components/LCAComponents/SectionDetail.tsx
Labels: 분류: 버그

#92 HOMEPAGE-26 [FeatDone] Update to link to /product/cis
  components/LayoutComponents/Hamburger/HamburgerMenu.tsx
  components/LayoutComponents/NavBar.tsx
  pages/index.tsx
  styles/commonStyles.ts
Labels: 분류: 기능 구현

#93 [ETC] Improve performance of image loading
  components/LayoutComponents/Hamburger/HamburgerMenu.tsx
  components/LayoutComponents/NavBar.tsx
  components/Products/CietLanding/Process/CietProcessSection.tsx
  components/Products/CietLanding/Process/NormalProcessSection.tsx
  components/Products/CietLanding/Process/SharedStyle.ts
  components/Products/CisLanding/Features/Details/Feature.tsx
  components/Products/CisLanding/Intro/Intro.tsx
  components/Products/CisLanding/ShortCut/ShortCut.tsx
  components/Products/CisLanding/UseCase/UseCase1.tsx
  components/Products/CisLanding/UseCase/UseCase2.tsx
  components/Products/CisLanding/UseCase/UseCase3.tsx
  components/Products/Common/Report/Report.tsx
  package.json
  pages/product/ciet/index.tsx
  pages/product/cis/index.tsx
  yarn.lock
Labels: 분류: 기능 구현

#96 [FeatDone] Update imgs about greenerp features
  public/images/cis/feature_1.png
  public/images/cis/feature_2.png
  public/images/cis/feature_3.png
Labels: 분류: 기능 구현

#97 [ETC] Fix bug about LCA arrow direction and update grid layout
  components/HomeComponents/CardNonText/CarbonCycle.tsx
  components/HomeComponents/CardNonText/RightNonText.tsx
  components/HomeComponents/PcCards/PcCards.tsx
  components/HomeComponents/ProductButtons/ProductButtons.tsx
  public/images/lca/lca_logo.png
  public/images/lca/lca_result_summary.png
Labels: 분류: 기능 구현, 분류: 버그

#99 [BugFix] Fix lca arrow shown big when first rendering
  components/HomeComponents/CardNonText/CarbonCycle.tsx
Labels: 분류: 버그

#101 [FeatDone] Add click event to mobile card
  components/HomeComponents/MobileCards/MobileCards.tsx
Labels: 분류: 기능 구현

#106 [FeatDone] Add image zoom animation and update linked page of product tab
  components/HomeComponents/CardNonText/LeftNonText.tsx
  components/LayoutComponents/NavBar.tsx
  components/Products/CietLanding/Process/CietProcessSection.tsx
  components/Products/CisLanding/Features/Features.tsx
  components/Products/CisLanding/Intro/Intro.tsx
  components/Products/CisLanding/SharedStyle.ts
  components/Products/CisLanding/UseCase/UseCase1.tsx
  components/Products/CisLanding/UseCase/UseCase2.tsx
  components/Products/CisLanding/UseCase/UseCase3.tsx
  components/Products/Common/Summary/Summary.tsx
  public/images/ciet/desktop_company_result.png
  public/images/cis/cfp.png
  public/images/cis/dashboard.png
  public/images/cis/erp.png
  public/images/cis/example_1.png
  public/images/cis/example_2.png
  public/images/cis/example_3.png
  public/images/cis/intro_home.png
Labels: 분류: 기능 구현

#107 [FeatDone] Optimize img loading of beta info section
  components/Products/Common/BetaInfo/BetaInfo.tsx
  components/Products/Common/ReportModal/ReportModal.tsx
Labels: 분류: 기능 구현

#108 [FeatDone] Optimize image loading of report img
  components/LayoutComponents/Footer.tsx
  components/Products/Common/ReportModal/ReportModal.tsx
  pages/product/ciet/index.tsx
  pages/product/greenerp/index.tsx
  public/images/cis/feature_3.png
  styles/commonStyles.ts
Labels: 분류: 기능 구현

#109 [FeatDone] Update report img and text, fix greenerp feature section ui
  components/Products/CisLanding/Features/Details/Feature.tsx
  components/Products/CisLanding/Features/Features.tsx
  components/Products/Common/Report/Report.tsx
  public/images/ciet/report_2.png
  public/images/product/report_1.png
  public/images/product/report_2.png
Labels: 분류: 기능 구현

#110 [BugFix] Fix wrong img path
  components/Products/Common/Report/Report.tsx
Labels: 분류: 기능 구현

#111 [BugFix] Fix bugs about scroll snap
  components/LayoutComponents/Footer.tsx
  components/Products/CisLanding/Intro/Intro.tsx
Labels: 분류: 버그

#112 [FeatDone] Update UI of mobile ver ciet page & root page
  components/HomeComponents/CardNonText/RightNonText.tsx
  components/HomeComponents/MobileCards/MobileCards.tsx
  components/Products/CietLanding/Process/NormalProcessSection.tsx
Labels: 분류: 기능 구현

#114 [BugFix] Fix scroll is abnormal in intro section of greenerp page
  components/Products/CisLanding/Intro/Intro.tsx
Labels: 분류: 버그
